debug = true
log_level = "info"
channel_size = 100
tcp_port = "9997"
dtls_port = "9232"
grpc_port = "50051"
peer_with_gateway = true
default_gateway = "128.32.37.48:9997"
[[ros]]
local = "pub"
node_name = "demo_image_1"
topic_name = "/image_1"
topic_type = "sensor_msgs/msg/CompressedImage"
[[ros]]
local = "pub"
node_name = "demo_image_2"
topic_name = "/image_2"
topic_type = "sensor_msgs/msg/CompressedImage"
[[ros]]
local = "sub"
node_name = "demo_action_1"
topic_name = "/action_1"
topic_type = "std_msgs/msg/String"
[[ros]]
local = "sub"
node_name = "demo_action_2"
topic_name = "/action_2"
topic_type = "std_msgs/msg/String"
[database]
url = "custom database url"
