[package]
name = "core"
version = "0.0.1-beta"
authors = ["Eric Chen <kych@berkeley.edu>", "Jiachen Yuan <jcyuan_johnson@berkeley.edu>"]
description = "The application core code"
edition = "2021"

[dependencies]
utils = { path = "../utils" }

rand = "0.8.4"
log = "0.4.14"
pnet= { version = "0.31.0", features = ["std"] }
pnet_macros_support =  { version = "0.31.0" }
pnet_macros ={ version = "0.31.0" }
pnet_packet = { version = "0.31.0", features = ["std"] }
local-ip-address = "0.4.9"
kv = "0.24.0"
strum_macros = "0.24.3"
anyhow = "1.0.66"
derivative = "2.2.0"
strum = "0.24.1"
